[project]
name = "comfyui-stylegan-dfl"
description = "StyleGAN2 and StyleGAN3 support for ComfyUI, @dfl's fork with added features"
version = "1.0.1"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "ninja",
    "safetensors",
    "packaging",
]

[project.urls]
Repository = "https://github.com/dfl/ComfyUI-StyleGan"
Documentation = "https://github.com/dfl/ComfyUI-StyleGan#readme"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "dflfd"
DisplayName = "ComfyUI-StyleGan"
Icon = ""
